# Generated by Django 4.0.3 on 2022-04-05 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competicao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competicao',
            name='modalidade',
        ),
    ]
